development:
  adapter: postgresql
  encoding: unicode
  database: ember_tester_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ember_tester_test
  pool: 5
  username: root
  password:
